Game.MVC/Controllers/HomeController.cs
using Game.Common.Entities;
using Game.Core;
using Game.MVC.Models;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        ItemService itemService;

        public ActionResult Index()
        {
            itemService = new ItemService();
            var model = itemService.GetAll().ToList();
            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Autherize(Account user)
        {
            var ms = new MemberService();
            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                if (ms.Auth(new Member { Account = user.Name , Password = user.Password}))
                {
                    Session["Account"] = user.Name;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    user.LoginErrorMessage = "錯誤的使用者帳戶或密碼";
                    return View("Login", user);
                }
            }
        }
    }
}

Game.MVC/Controllers/ItemController.cs
using Game.Common.Entities;
using Game.Core;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Game.MVC.Controllers
{
    public class ItemController : Controller
    {
        ItemService itemService;

        // GET: Item
        public ActionResult Index()
        {
            itemService = new ItemService();
            var model = itemService.GetAll().ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Item model)
        {
            itemService = new ItemService();
            var chk = itemService.Add(model);
            if (chk)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound();
            }
        }

        public ActionResult Detail(int? id)
        {
            if (null == id)
            {
                return HttpNotFound();
            }

            itemService = new ItemService();
            var chk = itemService.Query((int)id);
            if (null == chk)
            {
                return HttpNotFound();
            }
            else
            {
                return View(chk);
            }
        }

        public ActionResult Edit(int? id)
        {
            if (null == id)
            {
                return HttpNotFound();
            }

            itemService = new ItemService();
            var chk = itemService.Query((int)id);
            if (null == chk)
            {
                return HttpNotFound();
            }
            else
            {
                return View(chk);
            }
        }

        [HttpPost]
        public ActionResult Edit(Item model)
        {
            itemService = new ItemService();
            var chk = itemService.Update(model);
            if (chk)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        public ActionResult Delete(int? id)
        {
            if (null == id)
            {
                return HttpNotFound();
            }

            itemService = new ItemService();
            var chk = itemService.Remove((int)id);
            if (chk)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound();
            }
        }

        public ActionResult Query()
        {
            itemService = new ItemService();
            var items = itemService.GetAll().ToList();

            ViewBag.Items = items.Select(x =>
                                  new SelectListItem()
                                  {
                                      Text = x.Name,
                                      Value = x.Id.ToString()
                                  });
            return View(new List<Item>());
        }

        [HttpPost]
        public ActionResult Query(int weight)
        {
            itemService = new ItemService();
            var items = itemService.GetAll().ToList();

            ViewBag.Items = items.Select(x =>
                                  new SelectListItem()
                                  {
                                      Text = x.Name,
                                      Value = x.Id.ToString()
                                  }); ;


            var model = itemService.QueryByWeight(weight).ToList();
            return View(model);
        }

        public ActionResult QueryByItem(int weight)
        {

            var model = itemService.QueryByWeight(weight).ToList();
            return View(model);

        }
    }
}

Game.MVC/Controllers/MemberController.cs
using Game.Common.Entities;
using Game.Core;
using System.Linq;
using System.Web.Mvc;

namespace Game.MVC.Controllers
{
    public class MemberController : Controller
    {
        MemberService memberService;

        // GET: Member
        public ActionResult Index()
        {
            memberService = new MemberService();
            var model = memberService.GetAll().ToList();
            return View(model);
        }

        //Add功能
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Member model)
        {
            memberService = new MemberService();
            var chk = memberService.Add(model);

            if (chk)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound();
            }
        }

        //Delete功能
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            memberService = new MemberService();
            var chk = memberService.Delete((int)id);
            if (chk)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound();
            }
        }


        //Details功能
        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            memberService = new MemberService();
            var chk = memberService.Query((int)id);
            if (chk == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(chk);
            }
        }

        //Edit功能
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            memberService = new MemberService();
            var chk = memberService.Query((int)id);
            if (chk == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(chk);
            }
        }

        [HttpPost]
        public ActionResult Edit(Member model)
        {
            memberService = new MemberService();
            var chk = memberService.Update(model);
            if (chk)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
    }
}

Game.MVC/Controllers/MonsterController.cs
using Game.Common.Entities;
using Game.Core;
using System.Linq;
using System.Web.Mvc;

namespace Game.MVC.Controllers
{
    public class MonsterController : Controller
    {
        MonsterService monsterService;

        // GET: Monster
        public ActionResult Index()
        {
            monsterService = new MonsterService();
            var model = monsterService.GetAll().ToList();
            return View(model);
        }

        //Add功能
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Monster model)
        {
            monsterService = new MonsterService();
            var chk = monsterService.Add(model);

            if (chk)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound();
            }
        }

        //Delete功能
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            monsterService = new MonsterService();
            var chk = monsterService.Delete((int)id);
            if (chk)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound();
            }
        }


        //Details功能
        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            monsterService = new MonsterService();
            var chk = monsterService.Query((int)id);
            if (chk == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(chk);
            }
        }

        //Edit功能
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            monsterService = new MonsterService();
            var chk = monsterService.Query((int)id);
            if (chk == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(chk);
            }
        }

        [HttpPost]
        public ActionResult Edit(Monster model)
        {
            monsterService = new MonsterService();
            var chk = monsterService.Update(model);
            if (chk)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

    }
}

Game.MVC/Controllers/TreasureController.cs
using Game.Common.Entities;
using Game.Core;
using System.Linq;
using System.Web.Mvc;

namespace Game.MVC.Controllers
{
    public class TreasureController : Controller
    {
        TreasureService treasureService;
        // GET: Treasure
        public ActionResult Index()
       {
           treasureService = new TreasureService();
            var model = treasureService.GetAll().ToList();
            return View(model);
        }
        
        //Add功能
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Treasure model)
        {
            treasureService = new TreasureService();
            var chk = treasureService.Add(model);

            if (chk)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound();
            }
        }

        //Delete功能
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            treasureService = new TreasureService();
            var chk = treasureService.Delete((int)id);
            if (chk)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound();
            }
        }


        //Details功能
        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            treasureService = new TreasureService();
            var chk = treasureService.Query((int)id);
            if (chk == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(chk);
            }
        }

        //Edit功能
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            treasureService = new TreasureService();
            var chk = treasureService.Query((int)id);
            if (chk == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(chk);
            }
        }

        [HttpPost]
        public ActionResult Edit(Treasure model)
        {
            treasureService = new TreasureService();
            var chk = treasureService.Update(model);
            if (chk)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        //合併
        public ActionResult MonsterItem()
        {
            treasureService = new TreasureService();
            var model = treasureService.QueryName();

            return View(model);
            }
        }
}

Game.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Game.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Game.MVC/Views/Home/Index.cshtml
@{
    Layout = null;
    if (Session["Account"] == null)
    {
        Response.Redirect("~/Home/Login");
    }
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <h1>Dashboard主畫面</h1>
        <br>
        @Html.ActionLink("Item Page", "Index", "Item")<br><br>
        @Html.ActionLink("Member Page", "Index", "Member")<br><br>
        @Html.ActionLink("Monster Page", "Index", "Monster")<br><br>
        @Html.ActionLink("Treasure Page", "Index", "Treasure")<br><br>
        
        <a href="@Url.Action("LogOut","Home")">會員登出</a>
    </div>
</body>
</html>

Game.MVC/Views/Home/Login.cshtml
@model Game.MVC.Models.Account
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <style>
        #login-div {
            position: absolute;
            left: 40%;
            top: 40%;
            border: 1px solid #ccc;
            padding: 10px 10px;
        }

        .field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    <div id="login-div">
        @using (Html.BeginForm("Autherize", "Home", FormMethod.Post))
        {
            <table>
                <tr>
                    <td></td>
                    <td style="text-decoration:underline">會員登入</td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Name)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.Name)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Name)</td>
                </tr>

                <tr>
                    <td>
                        @Html.LabelFor(model => model.Password)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.Password)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Password)</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <label class="field-validation-error">@Html.DisplayFor(model => model.LoginErrorMessage)</label>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" name="name" value="點此登入" />
                        <input type="reset" name="name" value="重新輸入" />
                    </td>
                </tr>
            </table>
        }
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>